name: visionquest
favicon: null
layout_spectrum: 0.05978083051741123
typography_spectrum: 0.710838834522292
title: VisionQuest - an idea
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44961746-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.29375750781036913
  lightness: 0.4530338591430336
  saturation: 0.27386912726797163
  rhythmicContrast: 0.9060169344302267
purpose: []
