name: visionquest
favicon: null
layout_spectrum: 0.48369
typography_spectrum: 0.75671
title: VisionQuest - an idea
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44961746-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2bb673'
    - '#000000'
    - '#282e7a'
    - '#fefefe'
    - '#bbbbbb'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
